services:
  db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      - MYSQL_DATABASE=ecommerce
      - MYSQL_ROOT_PASSWORD=tiger
    volumes:
      - ./init-db:/docker-entrypoint-initdb.d
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD","mysqladmin","ping","-h","localhost","-u","root","-p$MYSQL_ROOT_PASSWORD"]
      interval: 5s
      timeout: 5s
      retries: 10


  backend:
    build: ./backend
    container_name: spring-backend
    ports:
    - "8080:8080"
    env_file:
    - /backend/.env
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/ecommerce?allowPublicKeyRetrieval=true&useSSL=false
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5
  
  frontend:
    build: ./frontend
    container_name: vite-frontend
    ports:
    - "5173:5173"
    stdin_open: true
    tty: true
    depends_on:
      backend:
        condition: service_healthy

volumes:
  db_data:

